### PR TITLE
Styling

### PR DESCRIPTION
**Pull request by Ldhatter**
Added css styling across the app

### CODE REVIEW

**Comment by adriannadiaz** [comment]
WARNING in ./src/app/components/phonelog/view-phonelog/view-phonelog.component.css
(Emitted value instead of an instance of Error) postcss-custom-properties: /Users/annar/Documents/Education/Concordia/SOEN490/SocialWorker/angular-client/src/app/components/phonelog/view-phonelog/view-phonelog.component.css:52:5: variable ‘--light’ is undefined and used without a fallback
NonErrorEmittedError:


🐛 🐛 🐛 🐛 🐛 🐛 🐛 🐛 🐛 🐛

**Comment by adriannadiaz** [comment]
screen shot 2018-04-01 at 10 18 55 pm

Expansion panel does not expand

**Comment by Ldhatter** [comment]
@adriannadiaz  that's not the current state of the branch lol

screen shot 2018-04-01 at 10 18 50 pm

**Comment by adriannadiaz** [comment]
screen shot 2018-04-01 at 10 27 02 pm

**Comment by adriannadiaz** [comment]
@Ldhatter

**Comment by adriannadiaz** [comment]
div tab-content should be same size between Participants and Resources
screen shot 2018-04-01 at 10 34 57 pm
screen shot 2018-04-01 at 10 35 34 pm

**Comment by adriannadiaz** [comment]
The hints are overlapping when filling the fields
screen shot 2018-04-01 at 10 37 41 pm

**Comment by adriannadiaz** [comment]
I like font-weight:100 💜
screen shot 2018-04-01 at 10 39 50 pm

**Comment by Ldhatter** [comment]
@annarog  @adriannadiaz  thx warning is fixed in 29afc5e

**Comment by Ldhatter** [comment]
@adriannadiaz  
fixed active case files when empty d46f0c1

screen shot 2018-04-01 at 10 48 49 pm
screen shot 2018-04-01 at 10 51 13 pm

**Comment by Ldhatter** [comment]
@adriannadiaz Fixed tab margin in e2f2a37 
(put em instead of rem by mistake)

**Comment by Ldhatter** [comment]
@adriannadiaz fixed: name input margin in 5c73d70

**Pull request merged**
