### PR TITLE
Phone Log modal

### PR DESCRIPTION
**Pull request by Ldhatter**
Changes:

- toolbar phone log button opens modal
- add phone log has pronouns select dropdown
- add phone log has subject select dropdown

### CODE REVIEW

**Comment by adriannadiaz** [comment]
Buttons are too close
screen shot 2018-04-02 at 8 04 27 pm


Also modal should be unavailable upon logout ? 

screen shot 2018-04-02 at 8 03 30 pm

**Comment by adriannadiaz** [comment]
this is mandatory reading 🤖

https://books.google.ca/books?hl=en&lr=&id=gGyEOjkdpbYC&oi=fnd&pg=PP1&dq=hci+models+theories+and+frameworks&ots=6yvhztpQk1&sig=EMHf9zGILqygoU4Y_gOHFIEG_9M#v=onepage&q=hci%20models%20theories%20and%20frameworks&f=false

**Comment by adriannadiaz** [comment]
@Ldhatter The Edit Phonelog needs a dropdown for subject (reason for call)

**Comment by Ldhatter** [comment]
@adriannadiaz fixed the phone log displaying only when logged in and added margin in 4e0b551

**Comment by Ldhatter** [comment]
@adriannadiaz  fixed edit phonelog in 53f7df3

**Comment by Ldhatter** [comment]
@adrianna @annarog  i made some additional changes:
- removed notes from phone logs (logs only contain message field now)
- edited forms 

Waiting for the pr travis ci build to finish. If it passes and if you have no more reviews to add, this branch if ready to merge. thanks!

**Comment by adriannadiaz** [comment]
Very nice work, but there is still a bug. Phonecalls logged from the popped up modal (the corner button) **must also trigger a refresh of the phonelog page**

**Comment by Ldhatter** [comment]
@adriannadiaz thanks for the observation.

- when using the modal: AfterClosed the page does not refresh (this is to avoid losing any unsaved work when using the phone log modal)
- will attempt a shared [service event](https://stackoverflow.com/questions/34700438/global-events-in-angular) since using @Output bindings will not work across the current hierarchy between these components.

thanks!

**Pull request merged**
